# Generated by Django 5.2.11 on 2026-02-22 20:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.CharField(choices=[('Fuel', 'Fuel'), ('Maintenance', 'Maintenance'), ('Insurance', 'Insurance'), ('Repair', 'Repair'), ('Other', 'Other')], default='Other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount in Euro', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Amount must be greater than 0')])),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, help_text='Additional details about the expense')),
                ('odometer_reading_at_expense', models.PositiveIntegerField(blank=True, help_text='Car odometer reading when expense occurred', null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expense_receipts/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cars.car')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date'], name='expenses_ex_date_2850f8_idx'), models.Index(fields=['expense_type'], name='expenses_ex_expense_c83905_idx')],
            },
        ),
    ]
