# Generated by Django 5.2.11 on 2026-02-22 20:15

import cars.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], default='Petrol', max_length=20)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('CVT', 'CVT')], default='Manual', max_length=20)),
                ('initial_value', models.DecimalField(decimal_places=2, help_text='Initial purchase value in Euro', max_digits=10)),
                ('current_odometer_reading', models.PositiveIntegerField(default=0, help_text='Current Odometer Reading in km')),
                ('color', models.CharField(blank=True, max_length=30)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('vin', models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17, null=True, unique=True, validators=[cars.validators.vin_validator])),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='cars', to='cars.tag')),
            ],
            options={
                'ordering': ['-year', 'make', 'model'],
                'unique_together': {('make', 'model', 'year', 'vin')},
            },
        ),
    ]
